name: Pyflakes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes
    - name: Analyze code with pyflakes
      run: |
        pyflakes . > pyflakes-report.txt || true
        cat pyflakes-report.txt
        if [ -s pyflakes-report.txt ]; then
          echo "Pyflakes found issues."
          exit 1
        else
          echo "Pyflakes found no issues."
        fi
